name: Portfolio Action

on:
  workflow_dispatch:
      
jobs:
  web-deploy:

    name: Deploy Node Dev App
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
  
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        source_dir: ./build
        key: ${{ secrets.PIYUSH_PORTFOLIO }}
        known_hosts: ${{ secrets.SSH_HOST }}
        if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
        
    - name: deploy backend
      run: rsync -rva --rsh="ssh" * ubuntu@65.0.29.124:/var/www/piyushprajapati/html && ssh ubuntu@65.0.29.124 'cd /var/www/piyushprajapati/html'
